### PR TITLE
feat: dibbs algorithm migrations

### LINKED ISSUE #14: Data migrations for DIBBS_BASIC and DIBBS_ENHANCED Algorithms
## Summary
Create data migrations for the existing [DIBBs Algorithms](https://github.com/CDCgov/IDWA-RL/blob/main/src/recordlinker/linkage/algorithms.py) to add them to the new Algorithm tables.

## Acceptance Criteria
- [x] Alembic migrations for adding the two algorithms to the database

## Details / Tasks
We should be creating two rows in the Algorithms table, one for DIBBS_BASIC and another for DIBBS_ENHANCED.  Each Algorithm will have 2 passes in the Passes table that matches their current specification from the algorithms.py file.

## Background / Context
We should use the information from the [DIBBs RL internal report](https://docs.google.com/document/d/1Gwu8V6d2V0IlcK9KQf5kIHPcgoQudln3Y330cqfwJOc/edit#heading=h.5i32wk9voy4) for determining what the descriptions for these two algorithms should be.  @alhayward might have some ideas into this already.

## Dependencies
#13 needs to be completed first, as this is dependent on those tables.

### PR DESCRIPTION
**Pull request by cbrinson-rise8**
## Description
Create data migrations for the existing [DIBBs Algorithms](https://github.com/CDCgov/IDWA-RL/blob/main/src/recordlinker/linkage/algorithms.py) to add them to the new Algorithm tables.

## Related Issues
closes #14 

## Additional Notes
- main change is the new `...add_dibbs_algorithms.py` migration file. 
- also some small changes to the `revises` `id` on a few migrations to fix the ordering issues when upgrading or downgrading. I also adjusted some of the migrations code to fix some problems that were occurring when trying to downgrade

## Checklist
Please review and complete the following checklist before submitting your pull request:

- [x] I have ensured that the pull request is of a manageable size, allowing it to be reviewed within a single session.
- [x] I have reviewed my changes to ensure they are clear, concise, and well-documented.
- [x] I have updated the documentation, if applicable.
- [x] I have added or updated test cases to cover my changes, if applicable.
- [x] I have minimized the number of reviewers to include only those essential for the review.
- [x] I have notified teammates in the review thread to build awareness.

## Checklist for Reviewers
Please review and complete the following checklist during the review process:

- [ ] The code follows best practices and conventions.
- [ ] The changes implement the desired functionality or fix the reported issue.
- [ ] The tests cover the new changes and pass successfully.
- [ ] Any potential edge cases or error scenarios have been considered.

### CODE REVIEW

**Comment by cbrinson-rise8** [comment]
Note: I changed changed the `revises` number on a couple migrations to fix the ordering issue. I also had to adjust some of the migrations `drop_table` commands just because they were failing when running

**Comment by ericbuckley** [comment]
I see there were a few migration issues to mitigate before tackling the data migration, which looks great BTW.  Could you try merging main back into this branch and just check to make sure the migrations run without a hitch?

**Comment by cbrinson-rise8** [comment]
> I see there were a few migration issues to mitigate before tackling the data migration, which looks great BTW. Could you try merging main back into this branch and just check to make sure the migrations run without a hitch?

I just pulled main and rebased. I ran `alembic downgrade base` and then `alembic upgrade head` and didn't run into any issues. There were definitely ones earlier but I got them all and it seems to be good!

**Review by ericbuckley — APPROVED** [review]
Thanks for double-checking against main, good work!

**Pull request merged**
