### PR TITLE
link router

### PR DESCRIPTION
**Pull request by ericbuckley**
## Description
Removing linking specific API endpoints out of main and into `recordlinker.routes.link_router`

## Additional Notes
This is just a code reorg change, no net new functionality has been added.
- Create a new router for the linking API endpoints
- Create a new schema, `recordlinker.schemas.link` to store link request/response payload signatures
- Remove `recordlinker.base_service` and define new names, versions, descriptions for the Record Linker app in `recordlinker.main`
- renamed the FHIR api endpoint from `/link-record` to `/link/fhir`
- Removed the sample FHIR bundles for the FHIR endpoint

<--------------------- REMOVE THE LINES BELOW BEFORE MERGING --------------------->

## Checklist
Please review and complete the following checklist before submitting your pull request:

- [x] I have ensured that the pull request is of a manageable size, allowing it to be reviewed within a single session.
- [x] I have reviewed my changes to ensure they are clear, concise, and well-documented.
- [x] I have updated the documentation, if applicable.
- [x] I have added or updated test cases to cover my changes, if applicable.
- [x] I have minimized the number of reviewers to include only those essential for the review.

## Checklist for Reviewers
Please review and complete the following checklist during the review process:

- [ ] The code follows best practices and conventions.
- [ ] The changes implement the desired functionality or fix the reported issue.
- [ ] The tests cover the new changes and pass successfully.
- [ ] Any potential edge cases or error scenarios have been considered.

### CODE REVIEW

**Comment by cbrinson-rise8** [comment]
[This PR #80](https://github.com/CDCgov/RecordLinker/pull/102) also adds a `/link/fhir` endpoint that takes in a fhir bundle and returns a non-fhir response. Is your thought that this PR's `/link/fhir` endpoint is the way we want it instead?

**Comment by ericbuckley** [comment]
> @ericbuckley [PR #102 ](https://github.com/CDCgov/RecordLinker/pull/102) also adds a `/link/fhir` endpoint that takes in a fhir bundle and returns a non-fhir response. Is that still functionality we want after merging this in? Since this PR also creates a `/link/fhir` endpoint that responds a little differently.

@cbrinson-rise8 thanks for bringing this up, I've had some thoughts on this, but we haven't discussed this as a team yet.

On one hand, keeping the same signature (accept FHIR, return FHIR) allows us to maintain backwards compatibility with the DIBBs software as their pipeline concept has standardized messages into FHIR bundles.

On the other, we can't support possible matches if we return FHIR AND its easier for customers to wrap their heads around the `/link*` endpoints if they all return the same thing.

Maybe we want both?  `/link/fhir` and `/link/dibbs`?  What do you think?

**Comment by cbrinson-rise8** [comment]
> > @ericbuckley [PR #102 ](https://github.com/CDCgov/RecordLinker/pull/102) also adds a `/link/fhir` endpoint that takes in a fhir bundle and returns a non-fhir response. Is that still functionality we want after merging this in? Since this PR also creates a `/link/fhir` endpoint that responds a little differently.
> 
> @cbrinson-rise8 thanks for bringing this up, I've had some thoughts on this, but we haven't discussed this as a team yet.
> 
> On one hand, keeping the same signature (accept FHIR, return FHIR) allows us to maintain backwards compatibility with the DIBBs software as their pipeline concept has standardized messages into FHIR bundles.
> 
> On the other, we can't support possible matches if we return FHIR AND its easier for customers to wrap their heads around the `/link*` endpoints if they all return the same thing.
> 
> Maybe we want both? `/link/fhir` and `/link/dibbs`? What do you think?

@ericbuckley  Yeah I was thinking keeping both is a good idea just in case for now. Its also a quick low effort change if we want to remove it later.

**Comment by ericbuckley** [comment]
> > > @ericbuckley [PR #102 ](https://github.com/CDCgov/RecordLinker/pull/102) also adds a `/link/fhir` endpoint that takes in a fhir bundle and returns a non-fhir response. Is that still functionality we want after merging this in? Since this PR also creates a `/link/fhir` endpoint that responds a little differently.
> > 
> > 
> > @cbrinson-rise8 thanks for bringing this up, I've had some thoughts on this, but we haven't discussed this as a team yet.
> > On one hand, keeping the same signature (accept FHIR, return FHIR) allows us to maintain backwards compatibility with the DIBBs software as their pipeline concept has standardized messages into FHIR bundles.
> > On the other, we can't support possible matches if we return FHIR AND its easier for customers to wrap their heads around the `/link*` endpoints if they all return the same thing.
> > Maybe we want both? `/link/fhir` and `/link/dibbs`? What do you think?
> 
> @ericbuckley Yeah I was thinking keeping both is a good idea just in case for now. Its also a quick low effort change if we want to remove it later.

@cbrinson-rise8 ok sounds good.  In this PR I'll rename `/link/fhir` to `/link/dibbs`

**Review by cbrinson-rise8 — APPROVED** [review]

**Pull request merged**
